name: "Delayed Release"
guid: "b7decd4f-e20d-45f5-b16b-da6f55d456a1"
imageUrl: ""
version: "0.0.0.2"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "your-username"
overview: "A plugin for delayed release of media"
description: >
  A plugin that allows you to control when media becomes available in your library.

category: "General"
artifacts:
  - "Jellyfin.Plugin.DelayedRelease.dll"
changelog: |2-
  ### Initial Release ###
  - Basic plugin structure
